/**
 * generated by Xtext
 */
package org.gemoc.agro.validation;

import org.gemoc.agro.validation.AbstractActivitiesDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ActivitiesDSLValidator extends AbstractActivitiesDSLValidator {
}
